name: whatsapp_camera
description: This is a package to open a camera along with a photo gallery, to simplify the steps of the end user
version: 1.0.0
homepage: https://github.com/welitonsousa/whatsapp_camera
repository: https://github.com/welitonsousa/whatsapp_camera
issue_tracker: https://github.com/welitonsousa/whatsapp_camera/issues


environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  camera_camera: 2.0.2
  file_picker: 5.2.2
  flutter_sliding_up_panel: 2.0.1
  photo_gallery: 1.1.1
  photo_view: 0.14.0
  permission_handler: 10.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

